### PR TITLE
Add some tests

### PR DESCRIPTION
**Pull request by AlexChesters**
Run them with `grunt test` :smile:

### CODE REVIEW

**Comment by flesler** [comment]
Hi @AlexChesters, thanks a lot for contributing.
It looks good.
May I ask for 2 changes before merging?
- Can you [squash](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) the commits? It's cleaner if they are all just one commit that says something like "Implemented tests" or similar
- Could you remove is-random and just pass numbers? Unit tests should be deterministic, introducing randomness means they could pass and then fail, depending on chance.

**Comment by AlexChesters** [comment]
Hi @flesler,

Sure, that seems reasonable. Could you take another look? Thanks!

**Comment by flesler** [comment]
It's perfect Alex, thanks

**Comment by AlexChesters** [comment]
I'd hardly say perfect but I'll take it :wink:

**Pull request merged**
